project: "MethylGPT-Finetune-49k-Large"

# Pretrained checkpoint (medium/large: layer_size=256, 15M params)
pretrained_model_args_path: "/sci/labs/benjamin.yakir/netanel.azran/repos/MethylGPT/pretrained_models/large/methylGPT-medium/args.json"
pretrained_file: "/sci/labs/benjamin.yakir/netanel.azran/repos/MethylGPT/pretrained_models/large/methylGPT-medium/medium-best_model_epoch6.pt"

# Output
weights_save_path: "/sci/labs/benjamin.yakir/netanel.azran/repos/MethylGPT-Thesis/finetune_checkpoints/large_49k/"

# Data
probe_id_file: "/sci/labs/benjamin.yakir/netanel.azran/MethylGPT/data/cpg_ids/probe_ids_type3.csv"
data_dir: "/sci/labs/benjamin.yakir/netanel.azran/repos/MethylGPT-Thesis/data/finetune_49k_parquet"
train_file_name: "finetune49k_train.parquet"
valid_file_name: "finetune49k_val.parquet"
test_file_name: "finetune49k_test.parquet"
dataset: "finetune49k"
cpg_sites: 49156

# Training
mask_ratio: 0
mlm_wt: 0
weight_decay: 0.01
gradient_clip_val: 1.0
log_every_n_steps: 10
pretrained_lr: 1.0e-5
head_lr: 1.0e-4
train_batch_size: 32
valid_batch_size: 32
max_epochs: 50
mode: "train"
valid_ckpt_path: "None"
wandb: false
